### ISSUE TITLE
Reown latest Flutter SDK Issue (1.4.2 + 1)

### ISSUE THREAD

**Issue by Shyam-Kumar-GBXBP** [reown-com/reown_flutter#150]
**SDK Affected**

AppKit 

**Describe the bug**

In Sdk version(1.4.2 + 1) facing late initialization error once we go back and come to the  reown screen. This initialization works fine on sdk version 1.3.0. There is an issue while initiating the smart contract, its not behaving properly mainly for Coinbase wallet. Checked with the FL Appkit (example project its working fine) but when tried to implement the same logic still the issue persists. It would be great if the team can help us. Thank you.  @quetool 

**To Reproduce**

1st issue:
• In sdk version (1.4.2 + 1) once initialized in a screen going back and coming again its causing late initialization error (@walletdata already initialized) this dosent happen on 1.3.0
2nd issue:
• While initiating the smart contract, its not behaving properly mainly for Coinbase wallet because the topic value is not available and while initiating requestWriteContract it throws an null error.
• In Sdk version 1.3.0 used request method instead able to deeplink to coinbase but the transaction pop up to times and coinabase throws an error. 

**Smartphone (please complete the following information):**

 - Device: iPhone and android

**Comment by quetool** [comment]
Thanks @Shyam-Kumar-GBXBP! I'm going to take a look!

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you write up a little example code to reproduce first issue?

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool Any update on the issues ??

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP , I'm looking into it.

**Comment by Shyam-Kumar-GBXBP** [comment]
Thank you @quetool

**Comment by Shyam-Kumar-GBXBP** [comment]
Awesome @quetool Sure.

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you try `reown_appkit: ^1.4.2+2`?

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, I will look at those issue on a separated branch (new version) as it requires a bit more of investigation.

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool As I tested now the late init issue is Fixed and its working fine the wallet state is maintained. Thanks for the update. We are blocked on the other two mentioned issues its a road blocker for our launch.

**Comment by quetool** [comment]
I'll take a look at it today!

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you install this temporary dependency and let me know if Coinbase Wallet gets opened?

```
reown_appkit:
    git:
      url: https://github.com/reown-com/reown_flutter.git
      path: packages/reown_appkit
      ref: 7d7a8ef65e2ed47d6e959f8ac8921c084b02123b
```

**Comment by Shyam-Kumar-GBXBP** [comment]
@quetool When using this dependency the connect wallet button is greyed out and not able to select. Kindly check this one.

**Comment by quetool** [comment]
Thanks! It's fixed! Please try this one:

```
reown_appkit:
    git:
      url: https://github.com/reown-com/reown_flutter.git
      path: packages/reown_appkit
      ref: 19e246a134a928c69bf1643ddccd9289f7e08504
```
