### ISSUE TITLE
Flutter appkit

### ISSUE THREAD

**Issue by Sleechigo** [reown-com/reown_flutter#17]
**Describe the bug**
Invalid arguments(s): Type IMagicService is already registered inside getit.

**To Reproduce**
1. setup new flutter project
2. run flutter run, app works perfectly
3. add reown_appkit: ^1.1.0-beta01 into pubspec 
Overide coinbase wallet sdk
```
dependency_overrides:
  coinbase_wallet_sdk:
    git:
      url: https://github.com/WalletConnect/wallet-mobile-sdk.git
      path: flutter
      ref: beba5b377e32554f5c00ee08c4df509d9078dbf1
```

import  'package:reown_appkit/reown_appkit.dart';
set up connection
close app and run flutter run
app runs perfectly fine, but make any edit to app, reload app, then error occurs on red screen.
Invalid arguments(s): Type IMagicService is already registered inside getit.

**Expected behavior**
Invalid arguments(s): Type IMagicService is already registered inside getit.

error happens on Iphone, Andriod and Chrome

**Additional context**
