### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by plusema86** [reown-com/reown_flutter#26]
**Describe the bug**

I got this error when I try to run my app
pub-cache/hosted/pub.dev/reown_appkit-1.0.1/lib/modal/appkit_modal_impl.dart:116:3: Error: Type 'Logger' not found.

**To Reproduce**

update Reown dependencies on pubspec.yaml
```
  reown_walletkit: 1.0.2
  reown_appkit: 1.0.1

```
the pubspec.lock contains
  ```
reown_appkit:
    dependency: "direct main"
    description:
      name: reown_appkit
      sha256: "16d5ce70bd254db2b0fd837272438f240212caf0fadff17902834cfb6644dc26"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.1"
  reown_core:
    dependency: transitive
    description:
      name: reown_core
      sha256: f0dc4829b674afb3ccf3f8d6b16e5e268a9bc919034c2594c68daeae7e0aec34
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  reown_sign:
    dependency: transitive
    description:
      name: reown_sign
      sha256: "83b6e85d853e3b6371fc7e00f39914bee52fd0ed18636ea5e082184a23171f2d"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  reown_walletkit:
    dependency: "direct main"
    description:
      name: reown_walletkit
      sha256: "20f4490e801909e463e6a412bb64572bac091629e6641ec94213d4f83fb70186"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
```

if I rollback to reown_walletkit 1.0.1 everything works fine
